ncaaf = [
    'Air Force',
    'Akron',
    'Alabama',
    'Appalachian State',
    'Arizona',
    'Arizona State',
    'Arkansas',
    'Arkansas State',
    'Army',
    'Auburn',
    'Ball State',
    'Baylor',
    'Boise State',
    'Boston College',
    'Bowling Green State',
    'Brigham Young',
    'Buffalo',
    'California',
    'Central Michigan',
    'Charlotte',
    'Cincinnati',
    'Clemson',
    'Coastal Carolina',
    'Colorado',
    'Colorado State',
    'Connecticut',
    'Duke',
    'East Carolina',
    'Eastern Michigan',
    'Florida',
    'Florida Atlantic',
    'Florida International',
    'Florida State',
    'Fresno State',
    'Georgia',
    'Georgia Southern',
    'Georgia State',
    'Georgia Tech',
    'Hawaii',
    'Houston',
    'Illinois',
    'Indiana',
    'Iowa',
    'Iowa State',
    'Kansas',
    'Kansas State',
    'Kent State',
    'Kentucky',
    'LSU',
    'Liberty',
    'Louisiana',
    'Louisiana Tech',
    'Louisiana-Monroe',
    'Louisville',
    'Marshall',
    'Maryland',
    'Massachusetts',
    'Memphis',
    'Miami (FL)',
    'Miami (OH)',
    'Michigan',
    'Michigan State',
    'Middle Tennessee State',
    'Minnesota',
    'Mississippi State',
    'Missouri',
    'Navy',
    'Nebraska',
    'Nevada',
    'Nevada-Las Vegas',
    'New Mexico',
    'New Mexico State',
    'North Carolina',
    'North Carolina State',
    'North Texas',
    'Northern Illinois',
    'Northwestern',
    'Notre Dame',
    'Ohio',
    'Ohio State',
    'Oklahoma',
    'Oklahoma State',
    'Old Dominion',
    'Ole Miss',
    'Oregon',
    'Oregon State',
    'Penn State',
    'Pitt',
    'Purdue',
    'Rice',
    'Rutgers',
    'SMU',
    'San Diego State',
    'San Jose State',
    'South Alabama',
    'South Carolina',
    'South Florida',
    'Southern Mississippi',
    'Stanford',
    'Syracuse',
    'Temple',
    'Tennessee',
    'Texas',
    'Texas A&M',
    'Texas Christian',
    'Texas State',
    'Texas Tech',
    'Toledo',
    'Troy',
    'Tulane',
    'Tulsa',
    'UAB',
    'UCF',
    'UCLA',
    'USC',
    'UTEP',
    'UTSA',
    'Utah',
    'Utah State',
    'Vanderbilt',
    'Virginia',
    'Virginia Tech',
    'Wake Forest',
    'Washington',
    'Washington State',
    'West Virginia',
    'Western Kentucky',
    'Western Michigan',
    'Wisconsin',
    'Wyoming',
]

ncaab = [
    'Abilene Christian',
    'Air Force',
    'Akron',
    'Alabama A&M',
    'Alabama-Birmingham',
    'Alabama State',
    'Alabama',
    'Albany (NY)',
    'Alcorn State',
    'American',
    'Appalachian State',
    'Arizona State',
    'Arizona',
    'Little Rock',
    'Arkansas-Pine Bluff',
    'Arkansas State',
    'Arkansas',
    'Army',
    'Auburn',
    'Austin Peay',
    'Ball State',
    'Baylor',
    'Belmont',
    'Bethune-Cookman',
    'Binghamton',
    'Boise State',
    'Boston College',
    'Boston University',
    'Bowling Green State',
    'Bradley',
    'Brigham Young',
    'Brown',
    'Bryant',
    'Bucknell',
    'Buffalo',
    'Butler',
    'Cal Poly',
    'Cal State Bakersfield',
    'Cal State Fullerton',
    'Cal State Northridge',
    'California Baptist',
    'UC-Davis',
    'UC-Irvine',
    'UC-Riverside',
    'UC-Santa Barbara',
    'University of California',
    'Campbell',
    'Canisius',
    'Central Arkansas',
    'Central Connecticut State',
    'Central Florida',
    'Central Michigan',
    'Charleston Southern',
    'Charlotte',
    'Chattanooga',
    'Chicago State',
    'Cincinnati',
    'Citadel',
    'Clemson',
    'Cleveland State',
    'Coastal Carolina',
    'Colgate',
    'College of Charleston',
    'Colorado State',
    'Colorado',
    'Columbia',
    'Connecticut',
    'Coppin State',
    'Cornell',
    'Creighton',
    'Dartmouth',
    'Davidson',
    'Dayton',
    'Delaware State',
    'Delaware',
    'Denver',
    'DePaul',
    'Detroit Mercy',
    'Drake',
    'Drexel',
    'Duke',
    'Duquesne',
    'East Carolina',
    'East Tennessee State',
    'Eastern Illinois',
    'Eastern Kentucky',
    'Eastern Michigan',
    'Eastern Washington',
    'Elon',
    'Evansville',
    'Fairfield',
    'Fairleigh Dickinson',
    'Florida A&M',
    'Florida Atlantic',
    'Florida Gulf Coast',
    'Florida International',
    'Florida State',
    'Florida',
    'Fordham',
    'Fresno State',
    'Furman',
    'Gardner-Webb',
    'George Mason',
    'George Washington',
    'Georgetown',
    'Georgia Southern',
    'Georgia State',
    'Georgia Tech',
    'Georgia',
    'Gonzaga',
    'Grambling',
    'Grand Canyon',
    'Green Bay',
    'Hampton',
    'Hartford',
    'Harvard',
    'Hawaii',
    'High Point',
    'Hofstra',
    'Holy Cross',
    'Houston Baptist',
    'Houston',
    'Howard',
    'Idaho State',
    'Idaho',
    'Illinois-Chicago',
    'Illinois State',
    'Illinois',
    'Incarnate Word',
    'Indiana State',
    'Indiana',
    'Iona',
    'Iowa State',
    'Iowa',
    'Purdue-Fort Wayne',
    'IUPUI',
    'Jackson State',
    'Jacksonville State',
    'Jacksonville',
    'James Madison',
    'Kansas State',
    'Kansas',
    'Kennesaw State',
    'Kent State',
    'Kentucky',
    'La Salle',
    'Lafayette',
    'Lamar',
    'Lehigh',
    'Liberty',
    'Lipscomb',
    'Cal State Long Beach',
    'Long Island University',
    'Longwood',
    'Louisiana',
    'Louisiana-Monroe',
    'Louisiana State',
    'Louisiana Tech',
    'Louisville',
    'Loyola (IL)',
    'Loyola Marymount',
    'Loyola (MD)',
    'Maine',
    'Manhattan',
    'Marist',
    'Marquette',
    'Marshall',
    'Maryland-Baltimore County',
    'Maryland-Eastern Shore',
    'Maryland',
    'Massachusetts-Lowell',
    'Massachusetts',
    'McNeese State',
    'Memphis',
    'Mercer',
    'Merrimack',
    'Miami (FL)',
    'Miami (OH)',
    'Michigan State',
    'Michigan',
    'Middle Tennessee',
    'Milwaukee',
    'Minnesota',
    'Mississippi State',
    'Mississippi Valley State',
    'Mississippi',
    'Missouri-Kansas City',
    'Missouri State',
    'Missouri',
    'Monmouth',
    'Montana State',
    'Montana',
    'Morehead State',
    'Morgan State',
    'Mount St. Mary\'s',
    'Murray State',
    'Navy',
    'Omaha',
    'Nebraska',
    'Nevada-Las Vegas',
    'Nevada',
    'New Hampshire',
    'New Mexico State',
    'New Mexico',
    'New Orleans',
    'Niagara',
    'Nicholls State',
    'NJIT',
    'Norfolk State',
    'North Alabama',
    'North Carolina-Asheville',
    'North Carolina A&T',
    'North Carolina Central',
    'North Carolina-Greensboro',
    'North Carolina State',
    'North Carolina-Wilmington',
    'North Carolina',
    'North Dakota State',
    'North Dakota',
    'North Florida',
    'North Texas',
    'Northeastern',
    'Northern Arizona',
    'Northern Colorado',
    'Northern Illinois',
    'Northern Iowa',
    'Northern Kentucky',
    'Northwestern State',
    'Northwestern',
    'Notre Dame',
    'Oakland',
    'Ohio State',
    'Ohio',
    'Oklahoma State',
    'Oklahoma',
    'Old Dominion',
    'Oral Roberts',
    'Oregon State',
    'Oregon',
    'Pacific',
    'Penn State',
    'Pennsylvania',
    'Pepperdine',
    'Pittsburgh',
    'Portland State',
    'Portland',
    'Prairie View',
    'Presbyterian',
    'Princeton',
    'Providence',
    'Purdue',
    'Quinnipiac',
    'Radford',
    'Rhode Island',
    'Rice',
    'Richmond',
    'Rider',
    'Robert Morris',
    'Rutgers',
    'Sacramento State',
    'Sacred Heart',
    'Saint Francis (PA)',
    'Saint Joseph\'s',
    'Saint Louis',
    'Saint Mary\'s(CA)',
    'Saint Peter\'s',
    'Sam Houston State',
    'Samford',
    'San Diego State',
    'San Diego',
    'San Francisco',
    'San Jose State',
    'Santa Clara',
    'Seattle',
    'Seton Hall',
    'Siena',
    'South Alabama',
    'South Carolina State',
    'South Carolina Upstate',
    'South Carolina',
    'South Dakota State',
    'South Dakota',
    'South Florida',
    'Southeast Missouri State',
    'Southeastern Louisiana',
    'Southern California',
    'SIU Edwardsville',
    'Southern Illinois',
    'Southern Methodist',
    'Southern Mississippi',
    'Southern Utah',
    'Southern',
    'St. Bonaventure',
    'St. Francis (NY)',
    'St. John\'s(NY)',
    'Stanford',
    'Stephen F. Austin',
    'Stetson',
    'Stony Brook',
    'Syracuse',
    'Temple',
    'Tennessee-Martin',
    'Tennessee State',
    'Tennessee Tech',
    'Tennessee',
    'Texas A&M-Corpus Christi',
    'Texas A&M',
    'Texas-Arlington',
    'Texas Christian',
    'Texas-El Paso',
    'Texas-Rio Grande Valley',
    'Texas-San Antonio',
    'Texas Southern',
    'Texas State',
    'Texas Tech',
    'Texas',
    'Toledo',
    'Towson',
    'Troy',
    'Tulane',
    'Tulsa',
    'UCLA',
    'Utah State',
    'Utah Valley',
    'Utah',
    'Valparaiso',
    'Vanderbilt',
    'Vermont',
    'Villanova',
    'Virginia Commonwealth',
    'VMI',
    'Virginia Tech',
    'Virginia',
    'Wagner',
    'Wake Forest',
    'Washington State',
    'Washington',
    'Weber State',
    'West Virginia',
    'Western Carolina',
    'Western Illinois',
    'Western Kentucky',
    'Western Michigan',
    'Wichita State',
    'William & Mary',
    'Winthrop',
    'Wisconsin',
    'Wofford',
    'Wright State',
    'Wyoming',
    'Xavier',
    'Yale',
    'Youngstown State',
]

mlb = [
    'Arizona Diamondbacks',
    'Atlanta Braves',
    'Baltimore Orioles',
    'Boston Red Sox',
    'Chicago Cubs',
    'Chicago White Sox',
    'Cincinnati Reds',
    'Cleveland Indians',
    'Colorado Rockies',
    'Detroit Tigers',
    'Houston Astros',
    'Kansas City Royals',
    'Los Angeles Angels',
    'Los Angeles Dodgers',
    'Miami Marlins',
    'Milwaukee Brewers',
    'Minnesota Twins',
    'New York Mets',
    'New York Yankees',
    'Oakland Athletics',
    'Philadelphia Phillies',
    'Pittsburgh Pirates',
    'San Diego Padres',
    'San Francisco Giants',
    'Seattle Mariners',
    'St. Louis Cardinals',
    'Tampa Bay Rays',
    'Texas Rangers',
    'Toronto Blue Jays',
    'Washington Nationals'
]

nba = [
    'Atlanta Hawks',
    'Boston Celtics',
    'Brooklyn Nets',
    'Charlotte Hornets',
    'Chicago Bulls',
    'Cleveland Cavaliers',
    'Dallas Mavericks',
    'Denver Nuggets',
    'Detroit Pistons',
    'Golden State Warriors',
    'Houston Rockets',
    'Indiana Pacers',
    'Los Angeles Clippers',
    'Los Angeles Lakers',
    'Memphis Grizzlies',
    'Miami Heat',
    'Milwaukee Bucks',
    'Minnesota Timberwolves',
    'New Orleans Pelicans',
    'New York Knicks',
    'Oklahoma City Thunder',
    'Orlando Magic',
    'Philadelphia 76ers',
    'Phoenix Suns',
    'Portland Trail Blazers',
    'Sacramento Kings',
    'San Antonio Spurs',
    'Toronto Raptors',
    'Utah Jazz',
    'Washington Wizards'
]

nfl = [
    'Arizona Cardinals',
    'Atlanta Falcons',
    'Baltimore Ravens',
    'Buffalo Bills',
    'Carolina Panthers',
    'Chicago Bears',
    'Cincinnati Bengals',
    'Cleveland Browns',
    'Dallas Cowboys',
    'Denver Broncos',
    'Detroit Lions',
    'Green Bay Packers',
    'Houston Texans',
    'Indianapolis Colts',
    'Jacksonville Jaguars',
    'Kansas City Chiefs',
    'Los Angeles Chargers',
    'Los Angeles Rams',
    'Miami Dolphins',
    'Minnesota Vikings',
    'New England Patriots',
    'New Orleans Saints',
    'New York Giants',
    'New York Jets',
    'Oakland Raiders',
    'Philadelphia Eagles',
    'Pittsburgh Steelers',
    'San Francisco 49ers',
    'Seattle Seahawks',
    'Tampa Bay Buccaneers',
    'Tennessee Titans',
    'Washington Redskins'
]

nhl = [
    'Anaheim Ducks',
    'Arizona Coyotes',
    'Boston Bruins',
    'Buffalo Sabres',
    'Calgary Flames',
    'Carolina Hurricanes',
    'Chicago Blackhawks',
    'Colorado Avalanche',
    'Columbus Blue Jackets',
    'Dallas Stars',
    'Detroit Red Wings',
    'Edmonton Oilers',
    'Florida Panthers',
    'Los Angeles Kings',
    'Minnesota Wild',
    'Montreal Canadiens',
    'Nashville Predators',
    'New Jersey Devils',
    'New York Islanders',
    'New York Rangers',
    'Ottawa Senators',
    'Philadelphia Flyers',
    'Pittsburgh Penguins',
    'San Jose Sharks',
    'St. Louis Blues',
    'Tampa Bay Lightning',
    'Toronto Maple Leafs',
    'Vancouver Canucks',
    'Vegas Golden Knights',
    'Washington Capitals',
    'Winnipeg Jets'
]

mlbtup = [('Arizona Diamondbacks', 'Arizona Diamondbacks'), ('Atlanta Braves', 'Atlanta Braves'), ('Baltimore Orioles', 'Baltimore Orioles'), ('Boston Red Sox', 'Boston Red Sox'), ('Chicago Cubs', 'Chicago Cubs'), ('Chicago White Sox', 'Chicago White Sox'), ('Cincinnati Reds', 'Cincinnati Reds'), ('Cleveland Indians', 'Cleveland Indians'), ('Colorado Rockies', 'Colorado Rockies'), ('Detroit Tigers', 'Detroit Tigers'), ('Houston Astros', 'Houston Astros'), ('Kansas City Royals', 'Kansas City Royals'), ('Los Angeles Angels', 'Los Angeles Angels'), ('Los Angeles Dodgers', 'Los Angeles Dodgers'), ('Miami Marlins', 'Miami Marlins'), ('Milwaukee Brewers', 'Milwaukee Brewers'), ('Minnesota Twins', 'Minnesota Twins'), ('New York Mets', 'New York Mets'), ('New York Yankees', 'New York Yankees'), ('Oakland Athletics', 'Oakland Athletics'), ('Philadelphia Phillies', 'Philadelphia Phillies'), ('Pittsburgh Pirates', 'Pittsburgh Pirates'), ('San Diego Padres', 'San Diego Padres'), ('San Francisco Giants', 'San Francisco Giants'), ('Seattle Mariners', 'Seattle Mariners'), ('St. Louis Cardinals', 'St. Louis Cardinals'), ('Tampa Bay Rays', 'Tampa Bay Rays'), ('Texas Rangers', 'Texas Rangers'), ('Toronto Blue Jays', 'Toronto Blue Jays'), ('Washington Nationals', 'Washington Nationals')]
